### PR TITLE
Added convolution algorithm and updated readme and requirements file

### PR DESCRIPTION
**Pull request by ViciousDove19**
Hello, I wrote an algorithm for convoluting a kernel over an image. I used NumPy for array operations. This algorithm could be further used to implement gaussian blur and canny edge detection algorithms.

### CODE REVIEW

**Comment by mateuszz0000** [comment]
@ViciousDove19 Nice! Thanks for PR. Before merge could you provide some unit tests for `convolution` and `apply_convolution` functions?

**Comment by ViciousDove19** [comment]
I have never written a unit test. Would you be needing a different code file of the same? Where I test those functions?

**Comment by mateuszz0000** [comment]
Thank you for your PR. I am waiting for more :smiley: Regarding unittests please take a look imgprocalgs/tests directory for some examples.

**Comment by ViciousDove19** [comment]
Thank you Sir! You were a great help! I'll definitely contribute more with hopefully better code. Thanks again for your help.

**Comment by mateuszz0000** [comment]
Keep it up!

**Pull request merged**
